// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zerei.Infrastructure.Data;

#nullable disable

namespace Zerei.Infrastructure.Migrations
{
    [DbContext(typeof(ZereiDbContext))]
    [Migration("20260912235141_Seguidores")]
    partial class Seguidores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneroJogo", b =>
                {
                    b.Property<int>("GenerosId")
                        .HasColumnType("integer");

                    b.Property<int>("JogosId")
                        .HasColumnType("integer");

                    b.HasKey("GenerosId", "JogosId");

                    b.HasIndex("JogosId");

                    b.ToTable("GeneroJogo");
                });

            modelBuilder.Entity("JogoPlataforma", b =>
                {
                    b.Property<int>("JogosDisponiveisId")
                        .HasColumnType("integer");

                    b.Property<int>("PlataformasDisponiveisId")
                        .HasColumnType("integer");

                    b.HasKey("JogosDisponiveisId", "PlataformasDisponiveisId");

                    b.HasIndex("PlataformasDisponiveisId");

                    b.ToTable("JogoPlataforma");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Jogatina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhRejogada")
                        .HasColumnType("boolean");

                    b.Property<double?>("Horas")
                        .HasColumnType("double precision");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int?>("PlataformaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioJogoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlataformaId");

                    b.HasIndex("UsuarioJogoId");

                    b.ToTable("Jogatinas");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("CapaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhDlc")
                        .HasColumnType("boolean");

                    b.Property<bool>("Famoso")
                        .HasColumnType("boolean");

                    b.Property<int?>("JogoBaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("Metacritic")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RawgId")
                        .HasColumnType("integer");

                    b.Property<string>("RawgSlug")
                        .HasColumnType("text");

                    b.Property<double?>("TempoMedioHoras")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("JogoBaseId");

                    b.HasIndex("RawgId")
                        .IsUnique()
                        .HasFilter("\"RawgId\" IS NOT NULL");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Plataformas");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Seguidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeguidoId")
                        .HasColumnType("integer");

                    b.Property<int>("SeguidorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeguidoId");

                    b.HasIndex("SeguidorId", "SeguidoId")
                        .IsUnique();

                    b.ToTable("Seguidores");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.UsuarioJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Favorito")
                        .HasColumnType("boolean");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer");

                    b.Property<int?>("Nota")
                        .HasColumnType("integer");

                    b.Property<string>("Resenha")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("UsuarioJogos");
                });

            modelBuilder.Entity("GeneroJogo", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zerei.Domain.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JogoPlataforma", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosDisponiveisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zerei.Domain.Entities.Plataforma", null)
                        .WithMany()
                        .HasForeignKey("PlataformasDisponiveisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Genero", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Usuario", null)
                        .WithMany("GenerosPreferidos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Jogatina", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zerei.Domain.Entities.UsuarioJogo", "UsuarioJogo")
                        .WithMany("Jogatinas")
                        .HasForeignKey("UsuarioJogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("UsuarioJogo");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Jogo", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Jogo", "JogoBase")
                        .WithMany("Dlcs")
                        .HasForeignKey("JogoBaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JogoBase");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Seguidor", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Usuario", "SeguidoUsuario")
                        .WithMany()
                        .HasForeignKey("SeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zerei.Domain.Entities.Usuario", "SeguidorUsuario")
                        .WithMany()
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeguidoUsuario");

                    b.Navigation("SeguidorUsuario");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.UsuarioJogo", b =>
                {
                    b.HasOne("Zerei.Domain.Entities.Jogo", "Jogo")
                        .WithMany("UsuarioJogos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zerei.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioJogos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Jogo", b =>
                {
                    b.Navigation("Dlcs");

                    b.Navigation("UsuarioJogos");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("GenerosPreferidos");

                    b.Navigation("UsuarioJogos");
                });

            modelBuilder.Entity("Zerei.Domain.Entities.UsuarioJogo", b =>
                {
                    b.Navigation("Jogatinas");
                });
#pragma warning restore 612, 618
        }
    }
}
